services:
  sqlite:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
      - .:/aulas
    working_dir: /aulas
    stdin_open: true
    tty: true
    entrypoint: sqlite3
    command: ["/data/loja.db"]
